environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

install:
  - ps: Install-Product node 6.6.0 x64
  - npm install -g npm --silent
  - npm install -g gulp mocha --silent

build_script:
  - .\scripts\npm.bat install --force
  - gulp electron
  - gulp compile

test_script:
  - node --version
  - npm --version
  - .\scripts\test.bat
  - .\scripts\test-integration.bat
