environment:
  ATOM_SHELL_INTERNAL_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

install:
  - ps: Install-Product node 6.5.0 x64
  - npm install -g npm
  - npm install -g gulp mocha

build_script:
  - .\scripts\npm.bat install --force
  - gulp electron
  - gulp compile

test_script:
  - node --version
  - npm --version
  - .\scripts\test.bat
  - .\scripts\test-integration.bat
