language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: basaratali@gmail.com
  api_key:
    secure: CWfM+wJEc/aKiGKl8PC0+9p3E4G4WgkVdMqzA2EOTNCyytZPRIa9ltgiKRh2CTTFXiq+qZ/g/v52lVucXGOhrh2JWiXrCHIx0+MzyzTgPZJNQ/Rx2K3PWoW4vKjRzj7ZHtoVFRBsLGN3YgxM8YxjUbem+2E/SOIFaj38QHj9SOIo1a1QFOzA2M19Ss1auOrmjmeBdY8mMEynoyLdgnhrFhpkxpfbSz3m+dattE6iglKrxTNSOrj2Kd8ebSjNfWzK4skORoxkkWM9VczygaAd52Kx3cssAEQzdCmWCXMme69WrFAzcRSln6xonYmO4PhV+1d3hf4Ui1fit+bPeuUH+Os7LufSShvashvZaBpCS/AWX0poanL58vMcYhcKn1TW8XusXpcETfdSbcnQpfGYxf7m3Azpp29aQFVSZjQAzjpXDvQoHgheNJh+Iwx/G4UPnPwkzv94Bcg8J0ptx4FE3YqET9Vjeogg8lEqQu/qwu1n8IH/8Q6y31hAIsdoY0cbQ5CCaL5G2t9xTs0bQGeUTyZWwwIxVpzsTwL2tbSreniycSgTiXhrG0BvbX4h0jcLI0EQsIRxW2Ndg3VvC22QKBAad/zITEdpR92YqSBhcRFehkLtzFDLkSHmLK4nGaaR/HJuvc8Z7czyYQANcljOY8H7kpSGFhEmd1+tFDJF8Pc=
  on:
    tags: true
    all_branches: true
    repo: alm-tools/alm
